name: CI

on:
  push:
    branches: [main, tests]
  pull_request:
    branches: [main, tests]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build and test
        run: |
          go build ./...
          go test ./...
          
